name: GitHub Projects Automation with README Update

on:
  pull_request:
    types: [closed]

jobs:
  move-issue-to-done-and-update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: |
          echo "Pull Request merged, updating README."

      - name: Update README
        env: # Set an environment variable
          PR_BODY: ${{ github.event.pull_request.body }}
        run: ./.github/scripts/update_readme.sh

      