name: GitHub Projects Automation with README Update

on:
  pull_request:
    types: [closed]

jobs:
  move-issue-to-done-and-update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: |
          chmod u+x .github/scripts/update_readme.sh
          ./.github/scripts/update_readme.sh